
/**
 * Matrix, indexed by row first, and column second, because I think that will be easier for Guassian Elimination.
 */
class Matrix{
    /** Threshold for floats in Guassian Elimination. */
    epsilon = 1e-12;
    /** @param {number[][]} array_2d a list of the rows of the matrix; */
    static from(array_2d){
        let m = new Matrix(
            array_2d.length,
            array_2d[0].length,
        );
        for(let row = 0; row < m.w; row++){
            for(let col = 0; col < m.h; col++){
                m.set(row, col, array_2d[row][col]);
            }
        }
        return m;
    }
    static identity(height){
        let m = new Matrix(height, height);
        for(let row = 0; row < m.w; row++){
            m.set(row, row, 1);
        }
        return m;
    }
    /**
     * @param {number} height number of rows;
     * @param {number} width number of columns;
     */
    constructor(height, width){
        /** @type {number} */
        this.w = width;
        /** @type {number} */
        this.h = height;
        /** @type {Float64Array} */
        this.a = new Float64Array(height * width);
        /** @type {Number} */
        this.proxies = [];
        for(let i = 0; i < this.h; i++){
            this.proxies[i] = i;
        }
    }
    get(row, col){
        return this.a[row * this.w + col];
    }
    set(row, col, value){
        this.a[row * this.w + col] = value;
    }
    /** Use row proxies for getting. */
    get_p(row, col){
        row = this.proxies[row];
        return this.a[row * this.w + col];
    }
    /** Use row proxies for setting. */
    set_p(row, col, value){
        row = this.proxies[row];
        this.a[row * this.w + col] = value;
    }
    /** Swap rows `a` and `b`. Only changes `this.proxies`. */
    swap(a, b){
        const swap_item = this.proxies[a];
        this.proxies[a] = this.proxies[b];
        this.proxies[b] = swap_item;
    }
    /** Apply proxy swaps in place, so they are effected by non-proxy operations. */
    apply(){
        const old = this.a;
        this.a = new Float64Array(this.h * this.w);
        let i = 0;
        for(let row = 0; row < this.h; row++){
            const offset = (this.proxies[row] - row) * this.w;
            let j = i + offset;
            for(let col = 0; col < this.w; col++, i++, j++){
                this.a[j] = old[i];
            }
        }
        this.proxies = [];
        for(let i = 0; i < this.h; i++){
            this.proxies[i] = i;
        }
    }
    /** Does `this = this + that`. @param {Matrix} that */
    add(that){
        if(this.h !== that.h || this.w !== that.w){
            throw RangeError(`${this.h} x ${this.w} matrix cannot be added to ${that.h} x ${that.w} matrix.`);
        }
        for(let i = 0; i < this.a.length; i++){
            this.a[i] += that.a[i];
        }
        return this;
    }
    /** Gives `this * that`. @param {Matrix} that */
    mul(that){
        if(this.w !== that.h){
            throw RangeError(`${this.h} x ${this.w} matrix cannot be multiplied by ${that.h} x ${that.w} matrix.`);
        }
        const res = new Matrix(this.h, that.w);
        let i = 0;
        for(let row = 0; row < this.h; row++)
        for(let col = 0; col < that.w; col++, i++)
        for(let j = 0; j < this.w; j++){
            res.a[i] += this.get(row, j) * that.get(j, col);
        }
        return res;
    }
    /** On each value, do `value %= mod`. @param {number} mod */
    mod(mod){
        for(let i = 0; i < this.a.length; i++){
            this.a[i] %= mod;
        }
        return this;
    }
    /** For Guassian Elimination, gives `[this | that]`. @param {Matrix} that */
    append(that){
        if(this.h !== that.h){
            throw RangeError(`${this.h} x ${this.w} matrix cannot be appended to ${that.h} x ${that.w} matrix.`);
        }
        const res = new Matrix(this.h, this.w + that.w);
        let res_end = 0;
        let res_i = 0;
        let this_i = 0;
        let that_i = 0;
        for(let row = 0; row < this.h; row++){
            res_end += this.w;
            for(; res_i < res_end; res_i++, this_i++){
                res.a[res_i] = this.a[this_i];
            }
            res_end += that.w;
            for(; res_i < res_end; res_i++, that_i++){
                res.a[res_i] = that.a[that_i];
            }
        }
        return res;
    }
    /** Value generated by `guassian_elimination`. @type {boolean[]?} */
    pivot_rows = null;
    /** Value generated by `guassian_elimination`. @type {boolean[]?} */
    pivot_cols = null;
    /**
     * Do Guassian Elimination, in place.
     * @param {Number} mod the base for doing all arithmetic mod n;
     */
    *guassian_elimination(mod){
        const float = !mod;
        /** list of multiplicative inverses for 0 to n-1, mod n; 0 indicates a non-invertible number; */
        const inverses = [0];
        for(let i = 1; i < mod; i++){
            for(let j = 1; j < mod; j++){
                if((i * j) % mod === 1){
                    inverses[i] = j;
                    break;
                }
            }
        }
        /** @type {boolean[]} */
        const pivot_rows = Array(this.h).fill(false);
        this.pivot_rows = pivot_rows;
        /** @type {boolean[]} */
        const pivot_cols = Array(this.w).fill(false);
        this.pivot_cols = pivot_cols;
        let pivot_i = 0;
        let found = true;
        while(found){
            let pivot_row = 0;
            let pivot_col = 0;
            found = false;
            outer_for: for(; pivot_col < this.w; pivot_col++){
                if(pivot_cols[pivot_col]) continue;
                pivot_row = 0;
                for(; pivot_row < this.h; pivot_row++){
                    if(pivot_rows[pivot_row]) continue;
                    if(
                        float
                        ? this.get_p(pivot_row, pivot_col)
                        : inverses[this.get_p(pivot_row, pivot_col)]
                    ){
                        this.swap(pivot_row, pivot_i);
                        pivot_row = pivot_i;
                        
                        pivot_rows[pivot_i] = true;
                        pivot_cols[pivot_col] = true;
                        
                        found = true;
                        break outer_for;
                    }
                }
            }
            if(!found) break;
            
            const div = float
            ? (1 / this.get_p(pivot_row, pivot_col))
            : inverses[this.get_p(pivot_row, pivot_col)];
            
            // do first part of elimination;
            for(let row = pivot_row + 1; row < this.h; row++){
                const mul = float
                ? (div * -this.get_p(row, pivot_col))
                : ((div * (mod - this.get_p(row, pivot_col))) % mod);
                for(let col = 0; col < this.w; col++){
                    const value = this.get_p(row, col) + mul * this.get_p(pivot_row, col);
                    this.set_p(row, col, float
                        ? (Math.abs(value) < this.epsilon ? 0 : value)
                        : (((value % mod) + mod) % mod)
                    );
                }
            }
            
            pivot_i++;
            yield this;
        }
        
        // do the second part of elimination;
        const pivot_col_is = [];
        for(let i = 0; i < this.w; i++){
            if(pivot_cols[i]) pivot_col_is.push(i);
        }
        for(let i = pivot_i - 1; i > 0; i--){
            const p_col = pivot_col_is[i];
            const div = float
            ? (1 / this.get_p(i, p_col))
            : inverses[this.get_p(i, p_col)];
            for(let j = i - 1; j > -1; j--){
                const mul = float
                ? (div * -this.get_p(j, p_col))
                : ((div * (mod - this.get_p(j, p_col))) % mod);
                for(let col = 0; col < this.w; col++){
                    const value = this.get_p(j, col) + mul * this.get_p(i, col);
                    this.set_p(j, col, float
                        ? (Math.abs(value) < this.epsilon ? 0 : value)
                        : (((value % mod) + mod) % mod)
                    );
                }
            }
            yield this;
        }
        // normalize rows;
        for(let i = pivot_i - 1; i > -1; i--){
            const p_col = pivot_col_is[i];
            const div = float
            ? (1 / this.get_p(i, p_col))
            : inverses[this.get_p(i, p_col)];
            for(let col = 0; col < this.w; col++){
                const value = div * this.get_p(i, col);
                this.set_p(i, col, float
                    ? (Math.abs(value) < this.epsilon ? 0 : value)
                    : (((value % mod) + mod) % mod)
                );
            }
        }
        yield this;
    }
    /**
     * Finds the inverse of the {1}-inverse of the matrix.
     * @param {Number} mod the base for doing all arithmetic mod n;
     */
    inv(mod){
        const m = this.append(Matrix.identity(this.h));
        [...m.guassian_elimination(mod)];
        const inv_proxies = [];
        m.proxies.forEach((v,i) => inv_proxies[v] = i);
        const my_rows = [];
        for(let i = 0; i < m.h; i++){
            if(!m.pivot_rows) continue;
            my_rows.push(inv_proxies[i]);
        }
        const my_cols = [];
        for(let i = 0; i < m.h; i++){
            if(!m.pivot_cols) continue;
            my_cols.push(i);
        }
        console.log({
            my_rows,
            my_cols,
        });
        m.apply();
        const inv = new Matrix(this.h, this.w);
        for(let i = 0; i < this.a.length; i++){
            inv.a[i] = this.a[i];
        }
        for(let row_i = 0; row_i < my_rows.length; row_i++){
            const row = my_rows[row_i];
            for(let col_i = 0; col_i < my_cols.length; col_i++){
                const col = my_cols[col_i];
                inv.set(row, col, m.get(row, col + this.w));
            }
        }
        return inv;
    }
    toString(){
        const inv_proxies = [];
        this.proxies.forEach((v,i) => inv_proxies[v] = i);
        let s = "[";
        for(let row = 0; row < this.h; row++){
            s += "\n  [";
            for(let col = 0; col < this.w; col++){
                s += this.get_p(row, col) + ",";
            }
            s += "], (og ";
            s += inv_proxies[row];
            s += ")";
        }
        s += "\n]";
        return s;
    }
}

/** @type {HTMLButtonElement} */
const btn_start = document.querySelector(".start");
/** @type {HTMLButtonElement} */
const btn_next = document.querySelector(".next");
/** @type {HTMLSpanElement} */
const el_done = document.querySelector(".done");
/** @type {HTMLPreElement} */
const el_value = document.querySelector(".value");

/** @type {Matrix} */
let my_matrix;
/** @type {Generator<Matrix, void, unknown>} */
let iterator;

const example = [
    [4, 2, 3, 4],
    [1, 3, 2, 6],
    [5, 3, 2, 2],
    [5, 5, 5, 3],
];

const m = Matrix.from(example);
const inv = m.inv(7);
console.log("m", "" + m);
console.log("inv", "" + inv);
console.log("check", "" + m.mul(inv).mod(7).mul(m).mod(7));

btn_start.onclick = function(){
    my_matrix = Matrix.from(example).append(Matrix.identity(4));
    iterator = my_matrix.guassian_elimination(7);
    el_done.innerHTML = "no (just started)";
    el_value.innerHTML = my_matrix.toString();
}
btn_next.onclick = function(){
    const {value, done} = iterator.next();
    el_done.innerHTML = done ? "yes" : "no";
    el_value.innerHTML = value.toString();
}


